baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Beyond2Void'
theme = 'PaperMod'

[params]
ShowShareButtons = true
ShowReadingTime = true
enableEmoji = true

  [params.homeInfoParams]
  Title = "&#x1f44b;Welcome to Minye's Blog."
  Content = "Hi, this is Minye. I'm documenting my learning notes and life stories here."

  [[params.socialIcons]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/minyexu/"

  [[params.socialIcons]]
  name = "GitHub"
  url = "https://github.com/beyond2void"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[menus]
  [[menus.main]]
    name = 'Posts'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    name = 'Search'
    pageRef = '/search'
    weight = 2
  [[menus.main]]
    name = 'Archive'
    pageRef = '/archive'
    weight = 3
  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 4